/* DBSchemaView — 마이그레이션 DDL 생성기
 *
 * 대조 결과를 받아 SOURCE 를 TARGET 으로 만드는 스크립트를 방언별 문법으로 적는다.
 * 실행 순서가 어긋나면 제약 때문에 실패하므로 외래키 제거 → 테이블 삭제 → 테이블 추가 →
 * 컬럼 변경 → 키·인덱스 → 외래키 추가 순으로 묶는다.
 *
 * 파서는 실행 중인 DB 가 아니라 DDL 텍스트만 보므로 이름이 없는 제약은 관례에 맞춰 지어낸다.
 * 그런 문장은 경고로 함께 알린다. */
(function (global) {
  "use strict";

  const DIALECTS = [
    { id: "mysql", label: "MySQL / MariaDB" },
    { id: "postgres", label: "PostgreSQL" },
    { id: "mssql", label: "SQL Server" },
    { id: "oracle", label: "Oracle" },
    { id: "sqlite", label: "SQLite (제한)" }
  ];

  function quoteIdentifier(dialect, name) {
    const text = String(name || "");
    if (dialect === "mysql") return `\`${text.replace(/`/g, "``")}\``;
    if (dialect === "mssql") return `[${text.replace(/]/g, "]]")}]`;
    if (dialect === "sqlite") return `"${text.replace(/"/g, '""')}"`;
    return `"${text.replace(/"/g, '""')}"`;
  }

  function quoteLiteral(value) {
    return `'${String(value == null ? "" : value).replace(/'/g, "''")}'`;
  }

  function sanitize(name) {
    return String(name || "")
      .replace(/[^0-9A-Za-z가-힣_]/g, "_")
      .replace(/_+/g, "_")
      .replace(/^_|_$/g, "");
  }

  /* 이름이 없는 제약에 붙일 관례 이름. 실제 DB 의 이름과 다를 수 있다. */
  function conventionName(prefix, tableName, columns) {
    const base = [prefix, sanitize(tableName), ...columns.map(sanitize)].filter(Boolean).join("_");
    return base.length > 60 ? base.slice(0, 60) : base;
  }

  function makeWriter(dialect) {
    const q = (name) => quoteIdentifier(dialect, name);
    const notes = new Set();
    const lines = [];

    const ref = (table) => (table.schema ? `${q(table.schema)}.${q(table.name)}` : q(table.name));
    const columnList = (columns) => columns.map((name) => q(name)).join(", ");

    function autoClause(column) {
      if (!column.auto) return "";
      if (dialect === "mysql") return " AUTO_INCREMENT";
      if (dialect === "mssql") return " IDENTITY(1,1)";
      if (dialect === "sqlite") return "";
      if (/\bserial\b/i.test(column.type || "")) return "";
      return " GENERATED BY DEFAULT AS IDENTITY";
    }

    /* CREATE TABLE 과 ADD/MODIFY COLUMN 이 함께 쓰는 컬럼 정의 */
    function columnSql(column, options = {}) {
      // SQLite 의 자동 증가는 INTEGER PRIMARY KEY AUTOINCREMENT 한 가지 형태뿐이다.
      if (dialect === "sqlite" && column.auto && options.inlinePrimaryKey) {
        if (!/^integer$/i.test(column.type || "")) {
          notes.add(`SQLite 자동 증가는 INTEGER 만 허용해 ${column.name} 의 타입을 ${column.type} 에서 INTEGER 로 바꿨습니다.`);
        }
        return `${q(column.name)} INTEGER PRIMARY KEY AUTOINCREMENT`;
      }
      if (dialect === "sqlite" && column.auto) {
        notes.add(`SQLite 는 기본키가 아닌 ${column.name} 의 자동 증가를 표현하지 못합니다.`);
      }

      const parts = [q(column.name), column.type || "VARCHAR(255)"];

      if (column.generated) {
        notes.add(
          `${column.name} 은(는) 생성 컬럼입니다. 계산식은 DDL 원문에 남아 있지 않으므로 직접 채워야 합니다.`
        );
      }
      if (column.defaultValue) parts.push(`DEFAULT ${column.defaultValue}`);
      if (!column.nullable) parts.push("NOT NULL");
      const auto = autoClause(column);
      if (auto) parts.push(auto.trim());
      if (dialect === "mysql" && column.comment) parts.push(`COMMENT ${quoteLiteral(column.comment)}`);

      if (options.inlinePrimaryKey) parts.push("PRIMARY KEY");
      return parts.join(" ");
    }

    function section(title) {
      if (lines.length) lines.push("");
      lines.push(`/* ${title} */`);
    }

    function emit(text) {
      lines.push(text);
    }

    function comment(text) {
      lines.push(`-- ${text}`);
    }

    return { dialect, q, ref, columnList, columnSql, notes, lines, section, emit, comment, autoClause };
  }

  /* ------------------------------------------------------------ 문장 생성 */

  function createTableSql(writer, table) {
    const { q, ref, columnList, columnSql } = writer;
    const body = [];

    const pk = DBSchemaDiff.primaryKeyColumns(table);
    const singleAutoPk = writer.dialect === "sqlite" && pk.length === 1;

    for (const column of table.columns) {
      body.push(
        `  ${columnSql(column, { inlinePrimaryKey: singleAutoPk && column.pk })}`
      );
    }

    if (pk.length && !singleAutoPk) body.push(`  PRIMARY KEY (${columnList(pk)})`);

    for (const unique of DBSchemaDiff.uniqueConstraints(table)) {
      const name = unique.name || conventionName("uq", table.name, unique.columns);
      body.push(`  CONSTRAINT ${q(name)} UNIQUE (${columnList(unique.columns)})`);
    }

    // SQLite 는 나중에 외래키를 붙일 수 없어서 만들 때 함께 적는다.
    if (writer.dialect === "sqlite") {
      for (const relation of DBSchemaDiff.explicitRelations(table)) {
        body.push(`  ${foreignKeyClause(writer, relation)}`);
      }
    }

    const tail = writer.dialect === "mysql" && table.comment ? ` COMMENT=${quoteLiteral(table.comment)}` : "";
    return `CREATE TABLE ${ref(table)} (\n${body.join(",\n")}\n)${tail};`;
  }

  function foreignKeyClause(writer, relation, name) {
    const { q, ref, columnList } = writer;
    const parts = [];
    if (name) parts.push(`CONSTRAINT ${q(name)}`);
    parts.push(`FOREIGN KEY (${columnList(relation.fromColumns)})`);
    parts.push(`REFERENCES ${ref(relation.toTable)} (${columnList(relation.toColumns)})`);
    if (relation.onDelete) parts.push(`ON DELETE ${relation.onDelete}`);
    if (relation.onUpdate) {
      if (writer.dialect === "oracle") {
        writer.notes.add("Oracle 은 ON UPDATE 를 지원하지 않아 해당 절을 뺐습니다.");
      } else {
        parts.push(`ON UPDATE ${relation.onUpdate}`);
      }
    }
    return parts.join(" ");
  }

  function relationName(writer, relation) {
    if (relation.name) return relation.name;
    writer.notes.add("이름 없는 외래키는 관례 이름(fk_테이블_컬럼)으로 적었습니다. 실제 제약 이름을 확인하세요.");
    return conventionName("fk", relation.fromTable.name, relation.fromColumns);
  }

  function dropConstraintSql(writer, table, name, kind) {
    const { q, ref } = writer;
    if (writer.dialect === "mysql") {
      if (kind === "fk") return `ALTER TABLE ${ref(table)} DROP FOREIGN KEY ${q(name)};`;
      return `ALTER TABLE ${ref(table)} DROP INDEX ${q(name)};`;
    }
    return `ALTER TABLE ${ref(table)} DROP CONSTRAINT ${q(name)};`;
  }

  function addColumnSql(writer, table, column) {
    const { ref, columnSql } = writer;
    if (!column.nullable && !column.defaultValue && !column.auto) {
      writer.notes.add(
        `${table.name}.${column.name} 을(를) NOT NULL 로 추가합니다. 기존 행이 있으면 기본값을 먼저 정해야 합니다.`
      );
    }
    if (writer.dialect === "oracle") return `ALTER TABLE ${ref(table)} ADD (${columnSql(column)});`;
    if (writer.dialect === "mssql") return `ALTER TABLE ${ref(table)} ADD ${columnSql(column)};`;
    return `ALTER TABLE ${ref(table)} ADD COLUMN ${columnSql(column)};`;
  }

  function dropColumnSql(writer, table, columnName) {
    return `ALTER TABLE ${writer.ref(table)} DROP COLUMN ${writer.q(columnName)};`;
  }

  function alterColumnSql(writer, table, entry) {
    const { q, ref, columnSql } = writer;
    const column = entry.target;
    const changed = new Set(entry.changes.map((change) => change.field));
    const statements = [];

    if (writer.dialect === "mysql") {
      statements.push(`ALTER TABLE ${ref(table)} MODIFY COLUMN ${columnSql(column)};`);
      return statements;
    }

    if (writer.dialect === "postgres") {
      if (changed.has("type")) {
        statements.push(
          `ALTER TABLE ${ref(table)} ALTER COLUMN ${q(column.name)} TYPE ${column.type} USING ${q(
            column.name
          )}::${column.type};`
        );
      }
      if (changed.has("nullable")) {
        statements.push(
          `ALTER TABLE ${ref(table)} ALTER COLUMN ${q(column.name)} ${column.nullable ? "DROP NOT NULL" : "SET NOT NULL"};`
        );
      }
      if (changed.has("defaultValue")) {
        statements.push(
          column.defaultValue
            ? `ALTER TABLE ${ref(table)} ALTER COLUMN ${q(column.name)} SET DEFAULT ${column.defaultValue};`
            : `ALTER TABLE ${ref(table)} ALTER COLUMN ${q(column.name)} DROP DEFAULT;`
        );
      }
      return statements;
    }

    if (writer.dialect === "mssql") {
      if (changed.has("type") || changed.has("nullable")) {
        statements.push(
          `ALTER TABLE ${ref(table)} ALTER COLUMN ${q(column.name)} ${column.type || "VARCHAR(255)"} ${
            column.nullable ? "NULL" : "NOT NULL"
          };`
        );
      }
      if (changed.has("defaultValue")) {
        writer.notes.add(
          `SQL Server 의 기본값은 이름 있는 제약입니다. ${table.name}.${column.name} 은 기존 DEFAULT 제약을 먼저 지워야 합니다.`
        );
        if (column.defaultValue) {
          statements.push(
            `ALTER TABLE ${ref(table)} ADD CONSTRAINT ${q(
              conventionName("df", table.name, [column.name])
            )} DEFAULT ${column.defaultValue} FOR ${q(column.name)};`
          );
        }
      }
      return statements;
    }

    // Oracle: 바뀐 속성만 적는다. 이미 NOT NULL 인 컬럼에 NOT NULL 을 다시 주면 오류가 난다.
    const parts = [q(column.name)];
    if (changed.has("type")) parts.push(column.type || "VARCHAR2(255)");
    if (changed.has("defaultValue")) parts.push(`DEFAULT ${column.defaultValue || "NULL"}`);
    if (changed.has("nullable")) parts.push(column.nullable ? "NULL" : "NOT NULL");
    if (parts.length > 1) statements.push(`ALTER TABLE ${ref(table)} MODIFY (${parts.join(" ")});`);
    return statements;
  }

  /* 컬럼 설명을 다는 방법이 방언마다 다르다.
   * MySQL 은 컬럼 정의에 들어가므로 여기서는 다루지 않고,
   * SQL Server 는 확장 속성, SQLite 는 아예 문법이 없어 주석으로 남긴다. */
  function columnCommentSql(writer, table, column) {
    const { q, ref } = writer;
    const text = column.comment || "";

    if (writer.dialect === "postgres" || writer.dialect === "oracle") {
      return `COMMENT ON COLUMN ${ref(table)}.${q(column.name)} IS ${quoteLiteral(text)};`;
    }
    if (writer.dialect === "mssql") {
      const schema = table.schema || "dbo";
      if (!table.schema) writer.notes.add("SQL Server 컬럼 설명의 스키마를 dbo 로 가정했습니다.");
      return (
        `EXEC sp_addextendedproperty @name = N'MS_Description', @value = N${quoteLiteral(text)}, ` +
        `@level0type = N'SCHEMA', @level0name = N${quoteLiteral(schema)}, ` +
        `@level1type = N'TABLE', @level1name = N${quoteLiteral(table.name)}, ` +
        `@level2type = N'COLUMN', @level2name = N${quoteLiteral(column.name)};`
      );
    }
    writer.notes.add("SQLite 는 컬럼 설명 구문이 없어 주석으로만 남겼습니다.");
    return `-- ${table.name}.${column.name} 설명: ${text}`;
  }

  /* --------------------------------------------------------------- 조립 */

  function generate(diff, dialectId) {
    const dialect = DIALECTS.some((entry) => entry.id === dialectId) ? dialectId : "mysql";
    const writer = makeWriter(dialect);
    const label = DIALECTS.find((entry) => entry.id === dialect).label;

    if (!diff || !diff.tables.length) {
      return { sql: "-- 비교할 스키마가 없습니다.\n", notes: [], statementCount: 0 };
    }
    if (diff.identical) {
      return { sql: "-- 두 스키마가 같습니다. 생성할 변경이 없습니다.\n", notes: [], statementCount: 0 };
    }

    const added = diff.tables.filter((table) => table.status === "added");
    const removed = diff.tables.filter((table) => table.status === "removed");
    const changed = diff.tables.filter((table) => table.status === "changed");

    const sqlite = dialect === "sqlite";
    const recreateNeeded = new Set();

    /* 1. 외래키 제거 — 삭제될 테이블의 외래키는 DROP TABLE 이 함께 처리한다. */
    const fkDrops = [];
    for (const table of changed) {
      for (const relation of table.relations) {
        if (relation.status === "added") continue;
        const source = relation.source;
        if (!source) continue;
        if (sqlite) {
          recreateNeeded.add(table.qualified);
          continue;
        }
        fkDrops.push(dropConstraintSql(writer, table.source, relationName(writer, source), "fk"));
      }
    }
    if (fkDrops.length) {
      writer.section("1. 외래키 제거");
      for (const line of fkDrops) writer.emit(line);
    }

    /* 2. 테이블 삭제 */
    if (removed.length) {
      writer.section("2. 테이블 삭제 — 데이터가 함께 사라집니다");
      for (const table of removed) writer.emit(`DROP TABLE ${writer.ref(table.source)};`);
    }

    /* 3. 테이블 추가 */
    if (added.length) {
      writer.section("3. 테이블 추가");
      added.forEach((table, index) => {
        if (index) writer.emit("");
        writer.emit(createTableSql(writer, table.target));
        for (const index2 of DBSchemaDiff.plainIndexes(table.target)) {
          const name = index2.name || conventionName("idx", table.target.name, index2.columns);
          writer.emit(
            `CREATE INDEX ${writer.q(name)} ON ${writer.ref(table.target)} (${writer.columnList(index2.columns)});`
          );
        }
      });
    }

    /* 4. 컬럼 변경 */
    const columnLines = [];
    for (const table of changed) {
      const own = [];
      for (const entry of table.columns) {
        if (entry.status === "added") {
          own.push(addColumnSql(writer, table.target, entry.target));
        } else if (entry.status === "removed") {
          own.push(`-- 데이터가 사라집니다`);
          own.push(dropColumnSql(writer, table.target, entry.name));
        } else if (entry.status === "changed") {
          if (sqlite) {
            recreateNeeded.add(table.qualified);
            continue;
          }
          own.push(...alterColumnSql(writer, table.target, entry));
        }
      }
      if (own.length) columnLines.push({ table, own });
    }
    if (columnLines.length) {
      writer.section("4. 컬럼 변경");
      columnLines.forEach(({ table, own }, index) => {
        if (index) writer.emit("");
        writer.comment(table.qualified);
        for (const line of own) writer.emit(line);
      });
    }

    /* 5. 기본키 · 고유 제약 · 인덱스 */
    const keyLines = [];
    for (const table of changed) {
      const own = [];
      const reference = table.target;

      if (table.pk) {
        if (sqlite) {
          recreateNeeded.add(table.qualified);
        } else {
          if (table.pk.from.length) {
            if (dialect === "mysql" || dialect === "oracle") {
              own.push(`ALTER TABLE ${writer.ref(reference)} DROP PRIMARY KEY;`);
            } else {
              const name = dialect === "postgres" ? `${sanitize(reference.name)}_pkey` : conventionName("pk", reference.name, []);
              writer.notes.add(
                `${table.qualified} 의 기본키 제약 이름을 ${name} 으로 가정했습니다. 실제 이름을 확인하세요.`
              );
              own.push(dropConstraintSql(writer, reference, name, "pk"));
            }
          }
          if (table.pk.to.length) {
            own.push(`ALTER TABLE ${writer.ref(reference)} ADD PRIMARY KEY (${writer.columnList(table.pk.to)});`);
          }
        }
      }

      for (const unique of table.uniques) {
        if (sqlite) {
          recreateNeeded.add(table.qualified);
          continue;
        }
        const name = unique.name || conventionName("uq", reference.name, unique.columns);
        if (!unique.name) {
          writer.notes.add("이름 없는 고유 제약은 관례 이름(uq_테이블_컬럼)으로 적었습니다. 실제 이름을 확인하세요.");
        }
        if (unique.status === "added") {
          own.push(
            `ALTER TABLE ${writer.ref(reference)} ADD CONSTRAINT ${writer.q(name)} UNIQUE (${writer.columnList(
              unique.columns
            )});`
          );
        } else {
          own.push(dropConstraintSql(writer, reference, name, "unique"));
        }
      }

      for (const index of table.indexes) {
        const name = index.name || conventionName("idx", reference.name, index.columns);
        if (!index.name) {
          writer.notes.add("이름 없는 인덱스는 관례 이름(idx_테이블_컬럼)으로 적었습니다. 실제 이름을 확인하세요.");
        }
        if (index.status === "added") {
          own.push(`CREATE INDEX ${writer.q(name)} ON ${writer.ref(reference)} (${writer.columnList(index.columns)});`);
        } else if (dialect === "mysql") {
          own.push(`ALTER TABLE ${writer.ref(reference)} DROP INDEX ${writer.q(name)};`);
        } else if (dialect === "mssql") {
          own.push(`DROP INDEX ${writer.q(name)} ON ${writer.ref(reference)};`);
        } else {
          own.push(`DROP INDEX ${writer.q(name)};`);
        }
      }

      if (own.length) keyLines.push({ table, own });
    }
    if (keyLines.length) {
      writer.section("5. 기본키 · 제약 · 인덱스");
      keyLines.forEach(({ table, own }, index) => {
        if (index) writer.emit("");
        writer.comment(table.qualified);
        for (const line of own) writer.emit(line);
      });
    }

    /* 6. 외래키 추가 — 참조 대상이 모두 만들어진 뒤에 붙인다. */
    if (!sqlite) {
      const fkAdds = [];
      for (const table of added) {
        for (const relation of DBSchemaDiff.explicitRelations(table.target)) {
          fkAdds.push(
            `ALTER TABLE ${writer.ref(table.target)} ADD ${foreignKeyClause(writer, relation, relationName(writer, relation))};`
          );
        }
      }
      for (const table of changed) {
        for (const relation of table.relations) {
          if (relation.status === "removed") continue;
          const target = relation.target;
          fkAdds.push(
            `ALTER TABLE ${writer.ref(table.target)} ADD ${foreignKeyClause(writer, target, relationName(writer, target))};`
          );
        }
      }
      if (fkAdds.length) {
        writer.section("6. 외래키 추가");
        for (const line of fkAdds) writer.emit(line);
      }
    }

    /* 7. 설명 — MySQL 은 컬럼 정의에 함께 적히므로 컬럼 설명을 다시 낼 필요가 없다. */
    const commentLines = [];
    const inlineComments = dialect === "mysql";

    const tableComment = (table, text) => {
      if (dialect === "postgres" || dialect === "oracle") {
        return `COMMENT ON TABLE ${writer.ref(table)} IS ${quoteLiteral(text)};`;
      }
      if (dialect === "mysql") return `ALTER TABLE ${writer.ref(table)} COMMENT = ${quoteLiteral(text)};`;
      return null;
    };

    // 새로 만든 테이블은 CREATE 문에 설명을 넣지 못하는 방언이 있어 여기서 따로 붙인다.
    for (const table of added) {
      const line = table.target.comment ? tableComment(table.target, table.target.comment) : null;
      if (line && !inlineComments) commentLines.push(line);
      if (inlineComments) continue;
      for (const column of table.target.columns) {
        if (!column.comment) continue;
        commentLines.push(columnCommentSql(writer, table.target, column));
      }
    }

    for (const table of changed) {
      if (table.comment) {
        const line = tableComment(table.target, table.comment.to);
        if (line) commentLines.push(line);
      }
      if (inlineComments) continue;
      for (const entry of table.columns) {
        // 추가된 컬럼의 설명도 여기서 붙는다. ADD COLUMN 에는 들어가지 않는다.
        const carriesComment =
          (entry.status === "added" && entry.target.comment) ||
          (entry.status === "changed" && entry.changes.some((change) => change.field === "comment"));
        if (!carriesComment) continue;
        commentLines.push(columnCommentSql(writer, table.target, entry.target));
      }
    }
    if (commentLines.length) {
      writer.section("7. 설명");
      for (const line of commentLines) writer.emit(line);
    }

    /* SQLite 안내 */
    if (sqlite && recreateNeeded.size) {
      writer.section("SQLite 제약 — 아래 테이블은 재생성이 필요합니다");
      writer.comment("SQLite 는 컬럼 타입·기본키·제약 변경을 ALTER 로 처리하지 못합니다.");
      writer.comment("새 테이블 생성 → INSERT SELECT 로 복사 → 기존 테이블 DROP → RENAME 순서로 바꾸세요.");
      for (const name of recreateNeeded) writer.comment(`  · ${name}`);
      writer.notes.add(`SQLite 라서 ${recreateNeeded.size}개 테이블은 ALTER 로 바꾸지 못하고 재생성해야 합니다.`);
    }

    const stats = diff.stats;
    const header = [
      "-- DBSchemaView 마이그레이션 스크립트",
      `-- 방언: ${label}`,
      "-- 방향: SOURCE → TARGET (기준 스키마를 목표 스키마로 맞춥니다)",
      `-- 테이블 +${stats.addedTables} / -${stats.removedTables} / ~${stats.changedTables}` +
        ` · 컬럼 +${stats.addedColumns} / -${stats.removedColumns} / ~${stats.changedColumns}` +
        ` · 외래키 +${stats.addedRelations} / -${stats.removedRelations}`,
      "-- DDL 텍스트만 보고 만든 스크립트입니다. 실행 전에 반드시 검토하고 백업하세요.",
      "",
      ""
    ];

    const body = writer.lines.join("\n");
    const statementCount = writer.lines.filter((line) => line.trim().endsWith(";")).length;

    return {
      sql: `${header.join("\n")}${body}\n`,
      notes: [...writer.notes],
      statementCount
    };
  }

  global.DBSchemaDdl = { DIALECTS, generate };
})(globalThis);
